CREATE DATABASE pratica2;
USE pratica2;

CREATE TABLE ALN_ALUNO(
ALN_ID int(13) AUTO_INCREMENT,
ALN_NOME varchar(255),
ALN_CURSO varchar(255), 
ALN_SALA varchar(255),

CONSTRAINT PK_ALN_RA PRIMARY KEY (ALN_ID)
);

CREATE TABLE AUL_AULA(
AUL_NUM_SALA int(13),
AUL_NOME_PROFESSOR VARCHAR(255),
AUL_CURSO VARCHAR(255),
CONSTRAINT PK_AUL_NUM_SALA PRIMARY KEY (AUL_NUM_SALA)
);

CREATE TABLE AUL_ALN(
ALN_ID int(13),
AUL_NUM_SALA int(13),
CONSTRAINT FK_ALN_RA FOREIGN KEY (ALN_ID) REFERENCES ALN_ALUNO(ALN_ID),
CONSTRAINT FK_AUL_SALA FOREIGN KEY (AUL_NUM_SALA) REFERENCES AUL_AULA(AUL_NUM_SALA)
);
